### ISSUE TITLE
Different time formats for .remind

### ISSUE THREAD

**Issue by MaraJade** [exp-publishing/cloudbot-plugins#10]
Being able to use hours and days for the .remind command would be a lot easier than trying to convert to minutes (and getting it wrong most of the time).

**Comment by jaelsasser** [comment]
Looks like the only format that doesn't fire Luftie is `2h30` (it wants a trailing minutes/seconds at the end). That's done in a Cloudbot core function, though, and outside the plugin scope.

```
14:29 <Meat> .remind 2h37m: hi
14:29 <+LuftWaffel> (Meat) Alright, I'll remind you "hi" in 2 hours and 37 minutes!
```
