### ISSUE TITLE
Corrections glitch

### ISSUE THREAD

**Issue by thePatchyBeard** [exp-publishing/cloudbot-plugins#12]
I'm not even sure how to describe it.

 <MaraJade> s/manifested/manifests/
<+LuftWaffel> Correction, <MaraJade> s/manifests/manifests/

**Comment by jaelsasser** [comment]
If this pops again, could you you post the last ten or fifteen messages in the channel? (Maybe scrubbing out usernames/details if you're worried about it.)

**Comment by jaelsasser** [comment]
Fixed in 9f0e236d57509e00a9d287d120b41fe5f37e85c2.
