### ISSUE TITLE
.remind command GRAMMAR!

### ISSUE THREAD

**Issue by Nanoprober** [exp-publishing/cloudbot-plugins#14]
The error message explaining the bounds of the remind time period is

 "Sorry, remind input must be more then a minute, and less then one month. "

When it should be 

Sorry, remind input must be more **than** a minute, and less **than** one month. 

sorry to nitpick

**Comment by jaelsasser** [comment]
Fixed in 79362e316a5e7606515de13a5580b7c8e289aeb6. (This one I can blame on upstream...)
