### ISSUE TITLE
The reminder function is cumbersome and limited. 

### ISSUE THREAD

**Issue by Dejers** [exp-publishing/cloudbot-plugins#15]
If the syntax could have the mandatory colon removed separating the message from the time,  that'd be great. 

And a separate, but to related for its own thread, would be for the plug on to support reminders that can trigger more than a month later.

**Comment by jaelsasser** [comment]
Addressed in f2f01e798468ac49193e54178177829046643e14. The command's a fair bit more limited if you drop the `:` (only interprets the first word as the relative time), but it'll still work.

Month-long limit's gonna stay in there until I build out a settings library for Luftie.
