### ISSUE TITLE
Correction command abuse

### ISSUE THREAD

**Issue by thePatchyBeard** [exp-publishing/cloudbot-plugins#6]
The correction function allows for the corrections of other IRC user besides the command issuer.  This function is being used to harass users.  Please amend to only correct previous posts of the command issuer only.  Thank you.

**Comment by jaelsasser** [comment]
Fixed in commit ec7ce13bd792f006801e5bd88c46a477a51a006c

**Comment by ctwelve** [comment]
Testing shows issue is fixed.
