### ISSUE TITLE
Choose: Can not use phrases as choice options. Space acts as a choice separator.

### ISSUE THREAD

**Issue by fourbags** [exp-publishing/cloudbot-plugins#9]
Choose will look at each individual word as a different choice. ".choose 1 or 2 | 3 or 4" will not select between the two options (which was the old waffle functionality), but rather the 7 different words/characters (including "|"). The help seems to suggest that you can include choices inside [] or <> but that does not actually allow phrases to work. Space still acts as a separator and will choose randomly from any word.

Example:
01:22 fourbags: .choose [1 or 2], [3 or 4]
01:22 LuftWaffel: [3

**Comment by jaelsasser** [comment]
Spaces are now longer a valid separator as of 760a4136d36a4375c88a32ce213376bd12793805. @fourbags @ctwelve, do we also want to split on `|`?

(...next time I pull in a plugin to modify I'm gonna do it in two phases -- original file and our modifications.)
